apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-secret
  namespace: <namespace> #Reemplazar
stringData:
  host: "https://sonar-sonarqube.apps.<domain>" #Reemplazar
  token: "<token>" #Reemplazar
