apiVersion: v1
kind: Secret
metadata:
  name: user-at-github
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: "<username>" #Reemplazar
  password: "<password>" #Reemplazar
  email: "<email>" #Reemplazar
