apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: <namespace> #Reemplazar
stringData:
  token: "<token>" #Reemplazar
  server: "openshift-gitops-server-openshift-gitops.apps.<domain>" #Reemplazar
