apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
stringData:
  token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJ0ZWt0b24ta2NkOmFwaUtleSIsIm5iZiI6MTcyMTI2OTQ1NCwiaWF0IjoxNzIxMjY5NDU0LCJqdGkiOiJkMDMyOTJlYS05YmZlLTQ4YjgtODNlZi1kMDM4ZmU4YTljYjMifQ._4NYcecM0ZRbqXRd4x4r_bRis-ZSTPhkXMr8b8TaV7U"
  server: "openshift-gitops-server.openshift-gitops.svc.cluster.local:80" 
