apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: binding
spec:
  params:
    - name: gitrevision-tag
      value: $(extensions.branch_name) #Nombre de la rama que dividimos en el Trigger.
