apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
stringData:
  token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJ0ZWt0b24ta2NkOmFwaUtleSIsIm5iZiI6MTcyMTQ3NzAwMCwiaWF0IjoxNzIxNDc3MDAwLCJqdGkiOiIyZWUwZGJmNy02MzExLTQwODAtYmJhZS03MDdmMjY2OWNmN2UifQ.PkISq-qduqdzLr2KytCxWgtcTj4evCcPpxJCV0Sgj0o"
  server: "openshift-gitops-server.openshift-gitops.svc.cluster.local:80"
